### PR TITLE
Fixes

### PR DESCRIPTION
**Pull request by Saumya-Mishra9129**

### CODE REVIEW

**Comment by quozl** [comment]
Reviewed.

**Comment by Saumya-Mishra9129** [comment]
> Reviewed.

Thanks @quozl 
I am done with the changes here.
@chimosky @srevinsaju @JuiP  Please do a review.

**Comment by quozl** [comment]
https://github.com/sugarlabs/calculate-activity/pull/68/commits/15aa8391d8b11edebcbf8c5fa57d0052c19c51e6 commit message inadequate; should mention "Fix AttributeError: type object '_io.StringIO' has no attribute 'StringIO'" and the circumstances to reproduce it, e.g. plotting.  Reviewed.

**Comment by chimosky** [comment]
Reviewed, thanks.

Just noticed that dividing a number by another number when it's not divisible - return a whole number when divided - by that number returns a fraction and I don't think that should be the case, as if I came to do that I'd expect to get the floating point value of my division. @quozl what do you think?

**Comment by Saumya-Mishra9129** [comment]
> Just noticed that dividing a number by another number when it's not divisible - return a whole number when divided - by that number returns a fraction and I don't think that should be the case, as if I came to do that I'd expect to get the floating point value of my division.

Yeah I noticed same earlier as well. I also agree it should return a floating point value but I thought It is designed in the same way , but I don't know why.

**Comment by quozl** [comment]
Yes, `3/4+2/4` displays `5/4`.  This has been a longstanding feature, but I don't know when it was added.  I don't think a _real number_ (e.g. 1.25) is any better.  That's what you mean by floating point; as floating point is an internal representation.  Consider `1/3` which cannot be represented by floating point, but could be displayed as `0.3...` with perfect accuracy, but `0.3333333333` would be wrong.  Elementary school children are the target of this calculator.

**Comment by Saumya-Mishra9129** [comment]
@quozl @chimosky Please review f360e2f.

**Comment by quozl** [comment]
Re: f360e2f

`math.round` is also unavailable in Python 2, and the code is about 12 years old.  This hasn't worked for a while.

The Calculate function `round` is defined as "round(x), return the integer nearest to x."

Why not use the built-in function `round`?

**Comment by Saumya-Mishra9129** [comment]
> Why not use the built-in function round?

It will end up into recursion according to me. I will try to find if there is a way to do it with built in  `round` and will update you.

**Comment by quozl** [comment]
There is always a way.  Even if you can't change the name of the function in the source file, you can add a myround.py which contains a function myround which calls the built-in round, and then import myround.

**Comment by Saumya-Mishra9129** [comment]
@quozl Done in 43a17cc

**Comment by quozl** [comment]
Thanks.  Reviewed.  Approved.

**Comment by chimosky** [comment]
Reviewed, thanks.

**Comment by shaansubbaiah** [comment]
@Saumya-Mishra9129 Did this fix #67? (for creation of the table with pending issues)

**Comment by Saumya-Mishra9129** [comment]
> @Saumya-Mishra9129 Did this fix #67? (for creation of the table with pending issues)

Sorry for the delay. No it doesn't.

**Pull request merged**
