### PR TITLE
Enable Indic and Indian numerals for the activity

### PR DESCRIPTION
**Pull request by nswarup14**
Implements #47 

**Changes and Additions**
1) `calculate.py`
2) `layout.py`
3) `numParser.py`

**Updates**
The activity now based on the `LANG` env variable, chooses the display numerals on the calculator layout. Conversions between the standard form the Indic/Indian form is done when required and the result is displayed in the local numerals.

As per checklist:
- [x] prove the source code changes are not present now,
- [x] prove the feature is not present now in some other form,
After going through the codebase, I realized no such feature has been implemented.
- [x] describe a test case,
Rather than use `os.getenv('LANG', 'en_US.utf8')`, we can test the feature by assigning a `LANG` in the `numParser.py` script. On running the activity, the layout is shown with local numerals. 
Tested with Malyalam numerals and performed different mathematical 
- [x] verify the test case,
Attached screenshot for reference
Screenshot from 2019-06-19 17-59-58
- [x] make a pull request.
- [ ] merge PR,

### CODE REVIEW

**Comment by quozl** [comment]
Thanks.  Reviewed as at 9a28df5.  Needs a test by someone familiar with the numerals.

**Comment by nswarup14** [comment]
@quozl 
I'm familiar with _Kannada, Tamil and Malayalam_ numerals as I'm from the same region in India.
Could you kindly guide me how I can update my `LANG` env variable to test these numerals.
Right now, my default value for the same is `en_US.utf8`.

Thanks!

**Comment by quozl** [comment]
Thanks.  I can't test appearance easily, as I only know arabic
numerals.  Someone else will have to test, even if you do.

Testing different LANG values can be done with either;

* My Settings - Language, or

* export a new value for the LANG environment variable in .i18n file

**Comment by nswarup14** [comment]
For reference:
https://www.omniglot.com/language/numbers/kannada.htm (Kannada numerals)
https://www.omniglot.com/language/numbers/malayalam.htm (Malayalam numerals)
https://www.omniglot.com/language/numbers/hindi.htm (Devanagiri numerals)
https://www.omniglot.com/language/numbers/tamil.htm (Tamil numerals)
https://en.wikipedia.org/wiki/Eastern_Arabic_numerals#Numerals (Indic numerals)

**Comment by quozl** [comment]
@nswarup14, I've tested that I get numerals that I don't recognise, using different values for LANG.  Please change the module name from "numparser" to a word that describes what the module is for.  The module translates of digits between different locales.

@Aniket21mathur, @pro-panda, @yashagrawal3, would one of you please test.  I'm presuming you have relevant experience which I don't have.

**Comment by Aniket21mathur** [comment]
@nswarup14 will you please rebase it with master, I will like to test with Python 3 as well. Thanks!

**Comment by quozl** [comment]
No, please not yet.  We don't have packages for Python 3 testing, so we can't scale.  I regret merging the port to Python 3 pull request, I was hasty.

**Comment by Aniket21mathur** [comment]
Thanks Tested. Used my little knowledge of Sanskrit and Devanagri :grin: as well as the reference provided by @nswarup14. Looks great!

**Comment by pro-panda** [comment]
I'm familiar with Devanagari symbols. I've reviewed their addition. I've compared the rest of the symbols with the sources provided by @nswarup14

**Pull request merged**
