### PR TITLE
Allow activity to receive decimal inputs for trigonometric functions, in degrees mode

### LINKED ISSUE #44: Sin, cosine and tangent are expecting integers in Degrees mode
http://git.sugarlabs.org/calculate/mainline/merge_requests/18
https://bugs.sugarlabs.org/ticket/3078

- [x] prove the source code changes are not present now,
- [x] prove the fix is not present now in some other form,
- [ ] describe a test case,
- [ ] merge the fix,
- [ ] verify the test case,
- [ ] make a pull request,
- [ ] close the ticket 3078.

### PR DESCRIPTION
**Pull request by nswarup14**
Fixes #44 

**Changed Files**
1) `artparser.py`
2) `mathlib.py`
3) `calculate.py`

**Updates**
1) Now the activity is accepting decimal values for all trigonometric functions, in degrees mode. 
Examples : `atan(1.5) = 56.3099324`, `sin(30.76) = 0.511443073` and so on.
VirtualBox_Ubuntu 18 04_24_06_2019_21_04_36
As proof:

Thanks!
Tested on Ubuntu 18.04 and Sugar v0.114

### CODE REVIEW

**Comment by quozl** [comment]
Thanks.  Reviewed.

You're removing what was added for bugs.sugarlabs.org 1713 and 1909,
back in year 2010.  Can you confirm these bugs are still fixed?

https://github.com/sugarlabs/calculate-activity/commit/569b1093565bac92c6eaded7dad9442d878c09a9
https://bugs.sugarlabs.org/ticket/1713
https://bugs.sugarlabs.org/ticket/1909

**Comment by nswarup14** [comment]
@quozl 
Yes, #1713 was still unfixed whereas #1909 was fixed. (Please see [here](https://github.com/sugarlabs/calculate-activity/blob/master/functions.py#L321) and similarly for _square_ function [here](https://github.com/sugarlabs/calculate-activity/blob/master/functions.py#L497)).

I have identified what seemed to cause the problem for #1713. It has something to do with interconversions between `float` and `Decimal`. The patch ensures that the current #44 issue as well as #1713 is resolved.

Thanks!

**Comment by quozl** [comment]
Tested for #44.  Tested for #1713; pass  Tested for #1909; pass.  Reviewed.

**Comment by quozl** [comment]
Please write a new commit message?  I think this fixes #44 and #1713 only.

**Comment by nswarup14** [comment]
Yes, it fixes #44 and #1713.  I shall write a new commit message

Thanks

**Comment by pro-panda** [comment]
Thanks, not reviewed.

Please fix commit messages ;-)

**Comment by quozl** [comment]
Thanks.  Reviewed.

**Comment by quozl** [comment]
Rebased and partially pushed;

* 9144161 becomes 5b51052 by Kunal Arora with commit message rewritten,
* f9a4614 becomes 9d55e66.

However, I wasn't able to understand what you wanted to achieve in 9f8cdd3, could you please explain in the commit message?  In particular, line 233 and 290 contain "resstr", and I don't know what that means.

**Comment by nswarup14** [comment]
@quozl 
Thanks!
I think I ported the code wrong. I wanted to change the way the if condition was written because I found it confusing. In the process, I had left a variable name unassigned. 
I have corrected it and rebased my changes. https://github.com/sugarlabs/calculate-activity/pull/62/commits/d0e82d9f7242d95545b9bd91eedab9d95e30d9a6 now shows the right changes.

As for the commit message, what I meant was that the commit fixes both the present issue #44 as well as #1713 from bugs.sugarlabs.org.

Should I resolve the conflicts?

Thanks

**Comment by quozl** [comment]
Thanks.  What's the purpose of "else: pass"?

**Comment by quozl** [comment]
Is this pull request obsolete?  Overall change relative to _master_ is very small.

**Comment by nswarup14** [comment]
@quozl 
Some commits were partially pushed, hence the changes to master seem very little.
Once I get my testing environment completely setup, I shall test the changes once again.

I recall the last time I tested this, and behaviour was as expected. I was able input decimal values for trigonometric functions and got expected results.

Thanks

**Comment by quozl** [comment]
Thanks.  It was the pull request [Files changed](https://github.com/sugarlabs/calculate-activity/pull/62/files) tab that I looked at.  One line of change.

**Comment by nswarup14** [comment]
Yes, Files Changes tab currently has just one line of change.

**Comment by JuiP** [comment]
@quozl I think this PR should be closed. Tested for #44 , the port to python3 seems to have fixed the issue. 
5b51052, uses Decimal to convert; however `/` in python3 and python2 work differently.

**Comment by quozl** [comment]
Thanks.

**Pull request closed without merging**
