### PR TITLE
Fix issues occured while raising RuntimeError

### LINKED ISSUE #67: Typing random text instead of digits/variables throws an error.
Reproduce:
	Type random text (eg. sweetener) -> Hit Enter / Equals symbol (=)

Traceback:

```python
1592573782.228379 DEBUG Calculate: Result: RuntimeError("Variable 'sweetener' not defined", 0,
 5)
Traceback (most recent call last):
  File "/usr/share/sugar/activities/Calculate.activity/layout.py", line 133, in <lambda>
    lambda w: self._parent.process()],
  File "/usr/share/sugar/activities/Calculate.activity/calculate.py", line 552, in process
    self.set_error_equation(eqn)
  File "/usr/share/sugar/activities/Calculate.activity/calculate.py", line 444, in set_err
or_equation
    self.set_last_equation(eqn)
  File "/usr/share/sugar/activities/Calculate.activity/calculate.py", line 439, in set_las
t_equation
    self.layout.last_eq.set_buffer(eqn.create_lasteq_textbuf())
  File "/usr/share/sugar/activities/Calculate.activity/calculate.py", line 219, in create_
lasteq_textbuf
    resstr = str(self.result)
  File "/usr/share/sugar/activities/Calculate.activity/astparser.py", line 110, in __str__
    {'a': self.eqn[self._range[0] - 1: self._range[1] - 1],
TypeError: 'NoneType' object is not subscriptable
```

Tested on:
	Calculate 46, Sugar 0.117-3, Debian Bullseye/ unstable

### PR DESCRIPTION
**Pull request by shaansubbaiah**
eqn was added to RuntimeError, but not passed to the parent
class ParserError
Errors occured while ParserError tried subscripting on the missing eqn
variable
Fix adds the missing arguments while raising RuntimeError

Traceback:
```
1592573782.228379 DEBUG Calculate: Result: RuntimeError("Variable 'sweetener' not defined", 0,
 5)
Traceback (most recent call last):
  File "/usr/share/sugar/activities/Calculate.activity/layout.py", line 133, in <lambda>
    lambda w: self._parent.process()],
  File "/usr/share/sugar/activities/Calculate.activity/calculate.py", line 552, in process
    self.set_error_equation(eqn)
  File "/usr/share/sugar/activities/Calculate.activity/calculate.py", line 444, in set_err
or_equation
    self.set_last_equation(eqn)
  File "/usr/share/sugar/activities/Calculate.activity/calculate.py", line 439, in set_las
t_equation
    self.layout.last_eq.set_buffer(eqn.create_lasteq_textbuf())
  File "/usr/share/sugar/activities/Calculate.activity/calculate.py", line 219, in create_
lasteq_textbuf
    resstr = str(self.result)
  File "/usr/share/sugar/activities/Calculate.activity/astparser.py", line 110, in __str__
    {'a': self.eqn[self._range[0] - 1: self._range[1] - 1],
TypeError: 'NoneType' object is not subscriptable
```

Fixes #67

### CODE REVIEW

**Comment by shaansubbaiah** [comment]
@quozl @chimosky kindly review.

New output, the full variable is highlighted in red.
image

Need to figure out how to test L455 and L511 properly, I raised errors within the try statement and the above traceback didn't occur.

Perhaps it would also be better to omit `Error at , position: 0:` if `eqn` and `_range` are None?

**Comment by quozl** [comment]
Thanks.  Reviewed.

* [ ] commit message should explain how to reproduce,
* [ ] commit message should mention regression was introduced by https://github.com/sugarlabs/calculate-activity/commit/eb9d99a849d7b45fad771bdeb646280c40a0d101,
* [ ] commit message traceback should not be wrapped,
* [ ] not all calls to _ParserError_ constructor are fixed (recall that https://github.com/sugarlabs/calculate-activity/commit/eb9d99a849d7b45fad771bdeb646280c40a0d101 changed the arguments); checking them;

```log
$ git grep -n ParserError
astparser.py:43:class ParserError(Exception):
astparser.py:67:class ParseError(ParserError):
astparser.py:72:        ParserError.__init__(self, msg, start, eqn, end)
```

Pass.

```log
astparser.py:83:class WrongSyntaxError(ParserError):
astparser.py:88:        ParserError.__init__(self, _("Syntax Error."), start, end)
```

Fail.

```log
astparser.py:101:class RuntimeError(ParserError):
astparser.py:106:        ParserError.__init__(self, msg, start, eqn, end)
```

Pass.

```log
astparser.py:117:class ArgumentError(ParserError):
astparser.py:122:        ParserError.__init__(self, msg, 0, end)
astparser.py:528:                except ParserError as e:
astparser.py:675:        except (RuntimeError, ParserError) as e:
$ 
```

Fail.

* [x] all calls to _ParseError_ constructor are fixed (https://github.com/sugarlabs/calculate-activity/commit/eb9d99a849d7b45fad771bdeb646280c40a0d101 also changed the arguments); checking them;

```log
$ git grep -n ParseError
astparser.py:67:class ParseError(ParserError):
astparser.py:651:                raise ParseError(msg, e.offset - 1, eqn)
astparser.py:656:                raise ParseError(msg, 0, eqn)
astparser.py:680:            raise ParseError(msg, 0, eqn)
calculate.py:40:from astparser import AstParser, ParserError, ParseError, RuntimeError
calculate.py:487:                eq.result = ParseError(str(e), 0, "")
```

Pass.

For your interest, I was able to reproduce by typing _sweetener_ and pressing enter;

```log
Traceback (most recent call last):
  File "/usr/share/sugar/activities/Calculate.activity/calculate.py", line 853, in keypress_cb
    return f(self)
  File "/usr/share/sugar/activities/Calculate.activity/calculate.py", line 308, in <lambda>
    'Return': lambda o: o.process(),
  File "/usr/share/sugar/activities/Calculate.activity/calculate.py", line 552, in process
    self.set_error_equation(eqn)
  File "/usr/share/sugar/activities/Calculate.activity/calculate.py", line 444, in set_error_equation
    self.set_last_equation(eqn)
  File "/usr/share/sugar/activities/Calculate.activity/calculate.py", line 439, in set_last_equation
    self.layout.last_eq.set_buffer(eqn.create_lasteq_textbuf())
  File "/usr/share/sugar/activities/Calculate.activity/calculate.py", line 219, in create_lasteq_textbuf
    resstr = str(self.result)
  File "/usr/share/sugar/activities/Calculate.activity/astparser.py", line 110, in __str__
    (self.eqn[self._range[0] - 1: self._range[1] - 1],
TypeError: 'NoneType' object is not subscriptable
```

I agree the message could be improved.

**Comment by shaansubbaiah** [comment]
@quozl I have made changes as requested, kindly review again.

Turns out there were errors (extra '-1') in slicing while generating the message string `msg`, causing empty strings. 
I have also added slight adjustments to improve the message 
1) Move `self._msg` to a new line 
2) Display the `eqn` splice enclosed in apostrophes to make it more clear when there is no input. 
	i.e Pressing <kbd>ENTER</kbd> / <kbd>=</kbd> without entering input

Before:
before-format

After:
image

**Comment by shaansubbaiah** [comment]
Thanks for testing :) I think I can OR the `eqn` with the sliced `eqn` while printing to fix this.

**Comment by quozl** [comment]
Thanks.  Reviewed.

**Comment by shaansubbaiah** [comment]
OR'd with `self.eqn` incase the sliced `eqn` is empty.

Looks like this when entering 'sweetener='

image

**Comment by Saumya-Mishra9129** [comment]
Great , Thanks :)

**Pull request merged**
