### PR TITLE
Implement Color selection feature for the calculator layout

### PR DESCRIPTION
**Pull request by nswarup14**
Implements  #58 

**Changes**

1. `calculate.py`
2. `layout.py`
3. `toolbars.py`

**Features and changes**
Rather than having an option to recolor every single button, I grouped them into '5 sets' based on similarity and location.
Set 1 -:  `->`, `<-`, `<=` buttons
Set 2 -: The actual numpad
Set 3 -: `Clear` button
Set 4 -: `Arithmetic operators and brackets`
Set 5 -: `=` button

1. When the activity is loaded for the first time, the color settings are checked if present in the `data` directory of the activity, if not `default_color_constants` are loaded, with an alert message as well.

2. When the activity is closed, the layout color data is written to a file called `bg_color` in the `data` directory for future use.

3. Added a new `toolbar-color` to enable color selection for the different sets mentioned above.

4. The `toolbar-color` contains 5 buttons, one for each set. Each of the toolbar buttons calls a `Gtk.ColorSelectionWindow` dialog, which enables the user to choose the right bg color, by changing different parameters. The color dialog is set to be `modal`, thus preventing any interaction with the parent dialog, i.e the activity itself.

5. The foreground colors for the button fonts is calculated based on the background colors as and when they are updated. This is done by the `self.set_font_fg()` method. The foreground colors can be either black or white. (I couldn't use the `alpha` value as suggested by James because the the activity uses Gdk.Color, which is deprecated and does not have `alpha`. I have addressed this in a separate statement).

6. Tested the activity on Ubuntu 18.04 and sugar v0.112.

I request the community members to review, test and suggest changes. Thanks.

**Issues**
1. `Gdk.Color` is deprecated and it needs to be ported to `Gdk.RGBA`.
2. The icons I have choosen for the `toolbar-color` is not completely correct. But I was unable to find the right icons and the I'm not very good with designing as well, so I couldn't design them. I request others to  suggest the appropriate icons for the same.

Thanks

### CODE REVIEW

**Comment by quozl** [comment]
Thanks.  Some good ideas there, but not what was wanted in the issue.  Please re-read the issue and read the linked articles there.  In particular;
* it is only the number buttons and digits that are to be each uniquely coloured; the operation buttons need not be coloured,
* colours can remain as they are until they are customised.

I'd have other things to say about your patch, but I'll wait until you have the user experience settled before I work on that.

**Comment by nswarup14** [comment]
As per the checklist,

 - [x] add a way for the child to colour the number buttons, to reset to default, and to use a preset such as the resistor colour code,
 - [ ] use the selected colours for digits whenever they are shown, such as in the entry and equation windows,
 - [ ] ensure the colouring does not prevent the number from being seen, e.g. by fading the alpha in the centre of each number button,
 - [x] preserve the configuration in the activity instance data directory rather than the journal object.

Coming to the user experience, the user is can choose individual colors for each of the digits. The user can also reset back to the default set of colors.

I have ported from`Gdk.Color` to `Gdk.RGBA` where it pertained to this issue. I'm not sure how exactly to utilise `alpha` value of `Gdk.RGBA`, and would like some guidance on the topic.

The present code uses `Gtk.Entry` to enter equations. However `Gtk.Entry` does not have a way to color individual characters. We could perhaps use `Gtk.TextView` and utilise the feature of tags to color individual characters.

Thanks!

**Comment by quozl** [comment]
Thanks.  Tested user experience.

* [ ] the digits on the buttons are coloured, but not the buttons; if you've found research to suggest only the digits should be coloured, let me know,
* [ ] the default has changed from white to a set of colours you've chosen; my expectation was that the default would be white until the user had changed the colours, which I explained above as _colours can remain as they are until they are customised_,
* [ ] an alert appears on first use; this alert is not needed,
* [ ] the new toolbar buttons are black on dark gray, very hard to see,
* [ ] the new toolbar buttons are near the stop button; they might instead be in the activity menu,
* [ ] the new number buttons on the configuration button are furry,
* [ ] the colour dialog does not take the current value.

Alpha is the degree of transparency.  It only matters when you wish to draw with a degree of transparency.  When there is nothing to be left behind when drawing pixels, use an alpha of 1.0.

**Comment by nswarup14** [comment]
Modified Checklist
- [x] the digits on the buttons are coloured, but not the buttons; if you've found research to suggest only the digits should be coloured, let me know,
 - [x] the default has changed from white to a set of colours you've chosen; my expectation was that the default would be white until the user had changed the colours, which I explained above as colours can remain as they are until they are customised,
 - [x] an alert appears on first use; this alert is not needed,
 - [x] the new toolbar buttons are black on dark gray, very hard to see,
- [x]  the new toolbar buttons are near the stop button; they might instead be in the activity menu,
 - [ ] the new number buttons on the configuration button are furry,
 - [ ] the colour dialog does not take the current value.

> the colour dialog does not take the current value.

I did not understand what this point meant. What does it mean by current value?

> the new number buttons on the configuration button are furry,

I found the test buttons at a repository online, and I edited them a bit. Unfortunately I wasn't able to find or design `.svg` icons.

As for user experience,
Now there are two buttons, _Preset and Reset_. _Preset_ loads the preset color layout (resistor code colors), which already initialized in the program. _Reset_ resets it back to default white and gray background. The user can also select his own color combinations and this is stored in the `data/` of the activity.
Rather than use alpha, I have chosen to alternate the black and white of the foreground digit color, based on the brightness of the background button color. I felt this enables a user to see the numbers more clearly. 

Thanks!

**Comment by quozl** [comment]
Thanks.  Tried to test  10aa389a2d6684e06bcfe123286f909944d5c13f but could not;

```log
Traceback (most recent call last):
  File "/usr/bin/sugar-activity", line 5, in <module>
    activityinstance.main()
  File "/usr/lib/python2.7/dist-packages/sugar3/activity/activityinstance.py", line 178, in main
    module = __import__(module_name)
  File "/usr/share/sugar/activities/Calculate.activity/calculate.py", line 39, in <module>
    from layout import CalcLayout
  File "/usr/share/sugar/activities/Calculate.activity/layout.py", line 398
    width = button[2]
        ^
IndentationError: expected an indented block
```

> What does it mean by current value?

* [ ] when the colour dialog is shown, it is not set to the colour already in use.

> found the test buttons online

Perhaps you might use a Gtk.Label instead of a Gtk.Icon in the buttons?  It will be rendered automatically using Pango and Cairo.

**Comment by nswarup14** [comment]
@quozl  Thanks
> when the colour dialog is shown, it is not set to the colour already in use.

The `Gtk.ColorSelectionDialog` does not seem to have methods to set color values that way.
Is it a necessary feature?
A user who wishes to change the color of a button, would pay no attention to its present value.

> Perhaps you might use a Gtk.Label instead of a Gtk.Icon in the buttons? It will be rendered automatically using Pango and Cairo.

I have used `Gtk.Label` with `set_markup()` method to specify the font specifications. The buttons look a lot cleaner.

Thanks!

**Comment by quozl** [comment]
> The `Gtk.ColorSelectionDialog` does not seem to have methods to set color values that way.

Yes, that's right.  It is delegated to the child _Gtk.ColorSelection_ widget instead.  Your code already uses that to read the colour values, so you should be able to write them.

> Is it a necessary feature?
> A user who wishes to change the color of a button, would pay no attention to its present value.

I disagree.  Tuning the colour would be an expected behaviour.  Also, at the moment the user will **lose** a colour choice just by starting to customise it?

I'm not sure we should be using the _Gtk.ColorSelection_ without reconsidering how we use the Toolkit colour selection widgets in Paint, Physics, and other activities that allow colour changes.  Calculate should be consistent with these, but the Toolkit widget is very primitive and hard to use.  Perhaps the Toolkit should acquire _Gtk.ColorSelection_ styled to fit Sugar.

> I have used `Gtk.Label` with `set_markup()` method to specify the font specifications. The buttons look a lot cleaner.

Consider refactoring the code; there is much repetition.

Tested https://github.com/sugarlabs/calculate-activity/pull/59/commits/2c629c99b0dddc0971f9d7fdb83c7f220d54de2a, failed to start, log has;

```log
Traceback (most recent call last):
  File "/usr/bin/sugar-activity", line 5, in <module>
    activityinstance.main()
  File "/usr/lib/python2.7/dist-packages/sugar3/activity/activityinstance.py", line 229, in main
    instance = create_activity_instance(activity_constructor, activity_handle)
  File "/usr/lib/python2.7/dist-packages/sugar3/activity/activityinstance.py", line 59, in create_activity_instance
    activity = constructor(handle)
  File "/usr/share/sugar/activities/Calculate.activity/calculate.py", line 392, in __init__
    self.layout = CalcLayout(self)
  File "/usr/share/sugar/activities/Calculate.activity/layout.py", line 87, in __init__
    self.preset_default_color(parent)
  File "/usr/share/sugar/activities/Calculate.activity/layout.py", line 107, in preset_default_color
    float(colors[2]), float(colors[3]))
ValueError: invalid literal for int() with base 10: 'set4'
```

**Comment by nswarup14** [comment]
@quozl Thanks!
The reason for the Traceback is that the activity is try to read from a file in the `data/` directory, that was perhaps created by 85338c19b88611a1da1dcd03573c60567d637a96.
https://github.com/sugarlabs/calculate-activity/pull/59/commits/2c629c99b0dddc0971f9d7fdb83c7f220d54de2a, however uses a different format of the file.
I suggest that the file be deleted from `data/` directory. The activity would then run.

**Comment by nswarup14** [comment]
@quozl 
I agree with `Gtk.ColorSelection` to be embedded into sugar-toolkit-gtk3. Shall I raise a corresponding issue on the github page?

Thanks

**Comment by quozl** [comment]
> The reason for the Traceback is that the activity is try to read from a file in the `data/` directory, that was perhaps created by [85338c1](https://github.com/sugarlabs/calculate-activity/commit/85338c19b88611a1da1dcd03573c60567d637a96).
> [2c629c9](https://github.com/sugarlabs/calculate-activity/commit/2c629c99b0dddc0971f9d7fdb83c7f220d54de2a), however uses a different format of the file.
> I suggest that the file be deleted from `data/` directory. The activity would then run.

Thanks.  We often have children turning off computers without shutting them down, and this may cause an empty file or file incomplete.  Please handle exception?

> I agree with `Gtk.ColorSelection` to be embedded into sugar-toolkit-gtk3. Shall I raise a corresponding issue on the github page?

Use an issue if you need agreement of others; e.g. agreement before coding.  Use a pull request if you have done coding.

**Comment by nswarup14** [comment]
> Please handle exception?

It has been handled [here](https://github.com/sugarlabs/calculate-activity/blob/cba82e54cdbe7f2449821ace6f43a0db6a67911b/layout.py#L98). The reason why the traceback was shown is that the `data/` directory happened to contain a file with the wrong format (The format was implemented in a previous commit, but has been changed in the later commits).

If a user opens the activity normally, the traceback wont be shown.

Thanks!

**Comment by quozl** [comment]
Thanks.  I will test an empty file and an incomplete file.

**Comment by quozl** [comment]
Tested cba82e5 with empty file.  Result is activity fails to start, traceback is a KeyError.  An empty file is expected if the disk is full at the time the configuration is changed.

**Comment by nswarup14** [comment]
@quozl 
Thanks.
I have fixed that in the latest patch.
Now the activity starts despite any or more of the following conditions
1) Incomplete file
2) Empty file
3) File not present in the right format

Thanks!

**Comment by quozl** [comment]
Thanks.  Reviewed 403465c.  It is an unusual method you've used; to get the size and check it instead of just count lines; because under certain rare circumstances a file can contain no lines and yet be non-zero size.  But I'll let it pass.

Tested as at 403465c on Ubuntu 19.04;

* [ ] the digits are not coloured in the button array, only the digit background colour is changed,
* [ ] the digits are not coloured in the entry box,
* [ ] the digits are not coloured in the result box,

Reviewed as at 403465c (the entire change set vs _master_);

* [ ] new code does not pass flake8 tests, but please don't fix flake8 warnings that aren't part of the change,
* [ ] the file name constant `'bg_color'` is in two different files,
* [ ] new icons 0 through 9 are drawn instead of using text capability of SVG, see https://github.com/sugarlabs/calculate-activity/pull/64/commits/476cbca86b7a4b3e5b464ccc17d9ddb0e028eba8, (and the new icons 0 through 9 are arabic only),

**Comment by nswarup14** [comment]
@quozl Thanks!
Modified checklist
 -[] the digits are not coloured in the button array, only the digit background colour is changed,
Yes, I feel this addresses the grapheme-color synthesia more suitably.
 -[] the digits are not coloured in the entry box,
 -[] the digits are not coloured in the result box,
Yes, in an earlier [comment](https://github.com/sugarlabs/calculate-activity/pull/59#issuecomment-497962045), I had mentioned of `Gtk.Entry` widgets could be replaced by `Gtk.TextView` which supports color encoding of characters. However, porting the equation entry box and the history box would be an enormous task that can perhaps be better managed in a separate PR.

Thanks!

**Comment by quozl** [comment]
Thanks.  Please fix conflicts against _master_ branch.

I'm fine with managing in a separate pull request if you think that will help; but I don't want to stall a future release of Calculate while waiting for complete feature implementation, so the procedure will be merging this pull request into a feature branch _synesthesia_ instead of _master_ then your further pull requests will be based on that branch and to that branch.  Okay with that?

**Comment by nswarup14** [comment]
@quozl
Thanks
Yes, having a feature branch called synthesia would be great, and further
work on the topic can be based on that branch.

**Comment by quozl** [comment]
I'll wait for you to fix conflicts against master.

**Comment by nswarup14** [comment]
@quozl 
I have resolved the conflicts against master.
Thanks

**Comment by quozl** [comment]
Thanks.  Pushed as branch synesthesia.  The commits are not squashed; eventually when we merge with master there should be one commit.  Remember to keep the synesthesia branch up to date with any changes to master, otherwise there will be a regression.

**Comment by nswarup14** [comment]
@quozl
Thanks
I shall keep keep the branch updated as changes to master take place.

**Pull request closed without merging**
